// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: internal/grpc/proto/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType_Type int32

const (
	DataType_COUPLE DataType_Type = 0
	DataType_TEXT   DataType_Type = 1
	DataType_BINARY DataType_Type = 2
	DataType_CARD   DataType_Type = 3
)

// Enum value maps for DataType_Type.
var (
	DataType_Type_name = map[int32]string{
		0: "COUPLE",
		1: "TEXT",
		2: "BINARY",
		3: "CARD",
	}
	DataType_Type_value = map[string]int32{
		"COUPLE": 0,
		"TEXT":   1,
		"BINARY": 2,
		"CARD":   3,
	}
)

func (x DataType_Type) Enum() *DataType_Type {
	p := new(DataType_Type)
	*p = x
	return p
}

func (x DataType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_keeper_proto_enumTypes[0].Descriptor()
}

func (DataType_Type) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_keeper_proto_enumTypes[0]
}

func (x DataType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType_Type.Descriptor instead.
func (DataType_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{0, 0}
}

type DataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{0}
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *Meta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Couple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta     *Meta  `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Id       int32  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Couple) Reset() {
	*x = Couple{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Couple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Couple) ProtoMessage() {}

func (x *Couple) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Couple.ProtoReflect.Descriptor instead.
func (*Couple) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *Couple) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Couple) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Couple) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Couple) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Couple) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNumber string `protobuf:"bytes,1,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"` //16-тизначный номер (в некоторых случаях 18-тизначный — включает зашифрованную информацию о банке-эмитенте)
	OwnerName  string `protobuf:"bytes,2,opt,name=ownerName,proto3" json:"ownerName,omitempty"`   //Имя и фамилия владельца на латинице
	ExpMonth   int32  `protobuf:"zigzag32,3,opt,name=ExpMonth,proto3" json:"ExpMonth,omitempty"`  //Срок действия: месяц
	ExpYear    int32  `protobuf:"zigzag32,4,opt,name=ExpYear,proto3" json:"ExpYear,omitempty"`    //Срок действия: год
	CVC        int32  `protobuf:"zigzag32,5,opt,name=CVC,proto3" json:"CVC,omitempty"`            //CVC или CVV2 — код из 3 или 4 цифр для совершения интернет-платежей, расположенный на обратной стороне
	Meta       *Meta  `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Id         int32  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Card) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Card) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *Card) GetCVC() int32 {
	if x != nil {
		return x.CVC
	}
	return 0
}

func (x *Card) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Card) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Binary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Meta  *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Id    int32  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *Binary) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Binary) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Binary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meta *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Id   int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Text) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// RegRequest запрос на регистрацию пользователя
type RegRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`       // логин для регистрации
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // пароль для регистрации
}

func (x *RegRequest) Reset() {
	*x = RegRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRequest) ProtoMessage() {}

func (x *RegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRequest.ProtoReflect.Descriptor instead.
func (*RegRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *RegRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegResponse ответ на регистрацию пользователя
type RegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegResponse) Reset() {
	*x = RegResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegResponse) ProtoMessage() {}

func (x *RegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegResponse.ProtoReflect.Descriptor instead.
func (*RegResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *RegResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`       // логин для авторизации
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // пароль для авторизации
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Couple   *Couple   `protobuf:"bytes,2,opt,name=couple,proto3" json:"couple,omitempty"`
	Card     *Card     `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	Binary   *Binary   `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`
	Text     *Text     `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CreateDataRequest) Reset() {
	*x = CreateDataRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataRequest) ProtoMessage() {}

func (x *CreateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataRequest.ProtoReflect.Descriptor instead.
func (*CreateDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDataRequest) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *CreateDataRequest) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

func (x *CreateDataRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *CreateDataRequest) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *CreateDataRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type CreateDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDataResponse) Reset() {
	*x = CreateDataResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataResponse) ProtoMessage() {}

func (x *CreateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataResponse.ProtoReflect.Descriptor instead.
func (*CreateDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{11}
}

type ReadDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *ReadDataRequest) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

type ReadDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Couple   *Couple   `protobuf:"bytes,2,opt,name=couple,proto3" json:"couple,omitempty"`
	Card     *Card     `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	Binary   *Binary   `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`
	Text     *Text     `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ReadDataResponse) Reset() {
	*x = ReadDataResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResponse) ProtoMessage() {}

func (x *ReadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResponse.ProtoReflect.Descriptor instead.
func (*ReadDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *ReadDataResponse) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *ReadDataResponse) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

func (x *ReadDataResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *ReadDataResponse) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *ReadDataResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type ReadAllDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
}

func (x *ReadAllDataRequest) Reset() {
	*x = ReadAllDataRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllDataRequest) ProtoMessage() {}

func (x *ReadAllDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllDataRequest.ProtoReflect.Descriptor instead.
func (*ReadAllDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *ReadAllDataRequest) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

type ReadAllDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Couples  []*Couple `protobuf:"bytes,2,rep,name=couples,proto3" json:"couples,omitempty"`
	Cards    []*Card   `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	Binaries []*Binary `protobuf:"bytes,4,rep,name=binaries,proto3" json:"binaries,omitempty"`
	Text     []*Text   `protobuf:"bytes,5,rep,name=text,proto3" json:"text,omitempty"`
}

func (x *ReadAllDataResponse) Reset() {
	*x = ReadAllDataResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllDataResponse) ProtoMessage() {}

func (x *ReadAllDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllDataResponse.ProtoReflect.Descriptor instead.
func (*ReadAllDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *ReadAllDataResponse) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *ReadAllDataResponse) GetCouples() []*Couple {
	if x != nil {
		return x.Couples
	}
	return nil
}

func (x *ReadAllDataResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ReadAllDataResponse) GetBinaries() []*Binary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

func (x *ReadAllDataResponse) GetText() []*Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"` // Тип обновляемой записи
	Id       int32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // Идентификатор обновляемой записи
	Couple   *Couple   `protobuf:"bytes,3,opt,name=couple,proto3" json:"couple,omitempty"`
	Card     *Card     `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Binary   *Binary   `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Text     *Text     `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDataRequest) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *UpdateDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDataRequest) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

func (x *UpdateDataRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *UpdateDataRequest) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *UpdateDataRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type UpdateDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"` // Тип обновленной записи
	Id       int32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // Идентификатор обновленной записи
	Couple   *Couple   `protobuf:"bytes,3,opt,name=couple,proto3" json:"couple,omitempty"`
	Card     *Card     `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Binary   *Binary   `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Text     *Text     `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDataResponse) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *UpdateDataResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDataResponse) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

func (x *UpdateDataResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *UpdateDataResponse) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *UpdateDataResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType *DataType `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"` // Тип обновляемой записи
	Id       int32     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // Идентификатор обновляемой записи
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDataRequest) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DeleteDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{19}
}

var File_internal_grpc_proto_keeper_proto protoreflect.FileDescriptor

var file_internal_grpc_proto_keeper_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x4f, 0x55, 0x50, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45,
	0x58, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x22, 0x1c, 0x0a, 0x04, 0x4d, 0x65,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75,
	0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xbe, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x08, 0x45, 0x78, 0x70, 0x4d, 0x6f, 0x6e,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x11, 0x52, 0x07, 0x45, 0x78, 0x70, 0x59, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x43, 0x56, 0x43, 0x18, 0x05, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x43, 0x56, 0x43, 0x12, 0x20,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x50, 0x0a, 0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4c, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x20,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3e, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x27, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x12, 0x26, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0xdf,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x22,
	0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0xe5, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x26,
	0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xe6, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a,
	0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63,
	0x6f, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x51, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xca, 0x03, 0x0a, 0x0d, 0x4b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x03,
	0x52, 0x65, 0x67, 0x12, 0x12, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x13, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x17, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x19, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_proto_keeper_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_keeper_proto_rawDescData = file_internal_grpc_proto_keeper_proto_rawDesc
)

func file_internal_grpc_proto_keeper_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_keeper_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_proto_keeper_proto_rawDescData)
	})
	return file_internal_grpc_proto_keeper_proto_rawDescData
}

var file_internal_grpc_proto_keeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_grpc_proto_keeper_proto_goTypes = []any{
	(DataType_Type)(0),          // 0: keeper.DataType.Type
	(*DataType)(nil),            // 1: keeper.DataType
	(*Meta)(nil),                // 2: keeper.Meta
	(*Couple)(nil),              // 3: keeper.Couple
	(*Card)(nil),                // 4: keeper.Card
	(*Binary)(nil),              // 5: keeper.Binary
	(*Text)(nil),                // 6: keeper.Text
	(*RegRequest)(nil),          // 7: keeper.RegRequest
	(*RegResponse)(nil),         // 8: keeper.RegResponse
	(*AuthRequest)(nil),         // 9: keeper.AuthRequest
	(*AuthResponse)(nil),        // 10: keeper.AuthResponse
	(*CreateDataRequest)(nil),   // 11: keeper.CreateDataRequest
	(*CreateDataResponse)(nil),  // 12: keeper.CreateDataResponse
	(*ReadDataRequest)(nil),     // 13: keeper.ReadDataRequest
	(*ReadDataResponse)(nil),    // 14: keeper.ReadDataResponse
	(*ReadAllDataRequest)(nil),  // 15: keeper.ReadAllDataRequest
	(*ReadAllDataResponse)(nil), // 16: keeper.ReadAllDataResponse
	(*UpdateDataRequest)(nil),   // 17: keeper.UpdateDataRequest
	(*UpdateDataResponse)(nil),  // 18: keeper.UpdateDataResponse
	(*DeleteDataRequest)(nil),   // 19: keeper.DeleteDataRequest
	(*DeleteDataResponse)(nil),  // 20: keeper.DeleteDataResponse
}
var file_internal_grpc_proto_keeper_proto_depIdxs = []int32{
	2,  // 0: keeper.Couple.meta:type_name -> keeper.Meta
	2,  // 1: keeper.Card.meta:type_name -> keeper.Meta
	2,  // 2: keeper.Binary.meta:type_name -> keeper.Meta
	2,  // 3: keeper.Text.meta:type_name -> keeper.Meta
	1,  // 4: keeper.CreateDataRequest.dataType:type_name -> keeper.DataType
	3,  // 5: keeper.CreateDataRequest.couple:type_name -> keeper.Couple
	4,  // 6: keeper.CreateDataRequest.card:type_name -> keeper.Card
	5,  // 7: keeper.CreateDataRequest.binary:type_name -> keeper.Binary
	6,  // 8: keeper.CreateDataRequest.text:type_name -> keeper.Text
	1,  // 9: keeper.ReadDataRequest.dataType:type_name -> keeper.DataType
	1,  // 10: keeper.ReadDataResponse.dataType:type_name -> keeper.DataType
	3,  // 11: keeper.ReadDataResponse.couple:type_name -> keeper.Couple
	4,  // 12: keeper.ReadDataResponse.card:type_name -> keeper.Card
	5,  // 13: keeper.ReadDataResponse.binary:type_name -> keeper.Binary
	6,  // 14: keeper.ReadDataResponse.text:type_name -> keeper.Text
	1,  // 15: keeper.ReadAllDataRequest.dataType:type_name -> keeper.DataType
	1,  // 16: keeper.ReadAllDataResponse.dataType:type_name -> keeper.DataType
	3,  // 17: keeper.ReadAllDataResponse.couples:type_name -> keeper.Couple
	4,  // 18: keeper.ReadAllDataResponse.cards:type_name -> keeper.Card
	5,  // 19: keeper.ReadAllDataResponse.binaries:type_name -> keeper.Binary
	6,  // 20: keeper.ReadAllDataResponse.text:type_name -> keeper.Text
	1,  // 21: keeper.UpdateDataRequest.dataType:type_name -> keeper.DataType
	3,  // 22: keeper.UpdateDataRequest.couple:type_name -> keeper.Couple
	4,  // 23: keeper.UpdateDataRequest.card:type_name -> keeper.Card
	5,  // 24: keeper.UpdateDataRequest.binary:type_name -> keeper.Binary
	6,  // 25: keeper.UpdateDataRequest.text:type_name -> keeper.Text
	1,  // 26: keeper.UpdateDataResponse.dataType:type_name -> keeper.DataType
	3,  // 27: keeper.UpdateDataResponse.couple:type_name -> keeper.Couple
	4,  // 28: keeper.UpdateDataResponse.card:type_name -> keeper.Card
	5,  // 29: keeper.UpdateDataResponse.binary:type_name -> keeper.Binary
	6,  // 30: keeper.UpdateDataResponse.text:type_name -> keeper.Text
	1,  // 31: keeper.DeleteDataRequest.dataType:type_name -> keeper.DataType
	7,  // 32: keeper.KeeperService.Reg:input_type -> keeper.RegRequest
	9,  // 33: keeper.KeeperService.Auth:input_type -> keeper.AuthRequest
	11, // 34: keeper.KeeperService.CreateData:input_type -> keeper.CreateDataRequest
	13, // 35: keeper.KeeperService.ReadData:input_type -> keeper.ReadDataRequest
	15, // 36: keeper.KeeperService.ReadAllData:input_type -> keeper.ReadAllDataRequest
	17, // 37: keeper.KeeperService.UpdateData:input_type -> keeper.UpdateDataRequest
	19, // 38: keeper.KeeperService.DeleteData:input_type -> keeper.DeleteDataRequest
	8,  // 39: keeper.KeeperService.Reg:output_type -> keeper.RegResponse
	10, // 40: keeper.KeeperService.Auth:output_type -> keeper.AuthResponse
	12, // 41: keeper.KeeperService.CreateData:output_type -> keeper.CreateDataResponse
	14, // 42: keeper.KeeperService.ReadData:output_type -> keeper.ReadDataResponse
	16, // 43: keeper.KeeperService.ReadAllData:output_type -> keeper.ReadAllDataResponse
	18, // 44: keeper.KeeperService.UpdateData:output_type -> keeper.UpdateDataResponse
	20, // 45: keeper.KeeperService.DeleteData:output_type -> keeper.DeleteDataResponse
	39, // [39:46] is the sub-list for method output_type
	32, // [32:39] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_keeper_proto_init() }
func file_internal_grpc_proto_keeper_proto_init() {
	if File_internal_grpc_proto_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_proto_keeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_keeper_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_keeper_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_keeper_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_keeper_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_keeper_proto = out.File
	file_internal_grpc_proto_keeper_proto_rawDesc = nil
	file_internal_grpc_proto_keeper_proto_goTypes = nil
	file_internal_grpc_proto_keeper_proto_depIdxs = nil
}
