// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: internal/grpc/proto/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType_Type int32

const (
	DataType_COUPLE DataType_Type = 0
	DataType_TEXT   DataType_Type = 1
	DataType_BINARY DataType_Type = 2
	DataType_CARD   DataType_Type = 3
)

// Enum value maps for DataType_Type.
var (
	DataType_Type_name = map[int32]string{
		0: "COUPLE",
		1: "TEXT",
		2: "BINARY",
		3: "CARD",
	}
	DataType_Type_value = map[string]int32{
		"COUPLE": 0,
		"TEXT":   1,
		"BINARY": 2,
		"CARD":   3,
	}
)

func (x DataType_Type) Enum() *DataType_Type {
	p := new(DataType_Type)
	*p = x
	return p
}

func (x DataType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_keeper_proto_enumTypes[0].Descriptor()
}

func (DataType_Type) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_keeper_proto_enumTypes[0]
}

func (x DataType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType_Type.Descriptor instead.
func (DataType_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{4, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{1}
}

type VerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	OTP   string `protobuf:"bytes,2,opt,name=OTP,proto3" json:"OTP,omitempty"`
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *VerifyRequest) GetOTP() string {
	if x != nil {
		return x.OTP
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verified bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type DataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{4}
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *Meta) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Couple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta     *Meta  `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Id       int32  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Couple) Reset() {
	*x = Couple{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Couple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Couple) ProtoMessage() {}

func (x *Couple) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Couple.ProtoReflect.Descriptor instead.
func (*Couple) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *Couple) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Couple) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Couple) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Couple) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Couple) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNumber string `protobuf:"bytes,1,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"` //16-тизначный номер (в некоторых случаях 18-тизначный — включает зашифрованную информацию о банке-эмитенте)
	OwnerName  string `protobuf:"bytes,2,opt,name=ownerName,proto3" json:"ownerName,omitempty"`   //Имя и фамилия владельца на латинице
	ExpMonth   int32  `protobuf:"zigzag32,3,opt,name=ExpMonth,proto3" json:"ExpMonth,omitempty"`  //Срок действия: месяц
	ExpYear    int32  `protobuf:"zigzag32,4,opt,name=ExpYear,proto3" json:"ExpYear,omitempty"`    //Срок действия: год
	CVC        int32  `protobuf:"zigzag32,5,opt,name=CVC,proto3" json:"CVC,omitempty"`            //CVC или CVV2 — код из 3 или 4 цифр для совершения интернет-платежей, расположенный на обратной стороне
	Meta       *Meta  `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Id         int32  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Card) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Card) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *Card) GetCVC() int32 {
	if x != nil {
		return x.CVC
	}
	return 0
}

func (x *Card) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Card) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Binary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Meta  *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Id    int32  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *Binary) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Binary) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Binary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Meta *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Id   int32  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Text) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`        // Логин
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`  // Пароль
	OTP      string `protobuf:"bytes,3,opt,name=OTP,proto3" json:"OTP,omitempty"`            // Одноразовый пароль
	Name     string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`          // Имя
	Phone    string `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`        // Номер телефона
	Email    string `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`        // Адрес электронной почты
	ID       int64  `protobuf:"varint,7,opt,name=ID,proto3" json:"ID,omitempty"`             // Уникальный идентификатор
	Verified bool   `protobuf:"varint,8,opt,name=Verified,proto3" json:"Verified,omitempty"` // Контактные данные подтверждены
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetOTP() string {
	if x != nil {
		return x.OTP
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// RegRequest запрос на регистрацию пользователя
type RegRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RegRequest) Reset() {
	*x = RegRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRequest) ProtoMessage() {}

func (x *RegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRequest.ProtoReflect.Descriptor instead.
func (*RegRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *RegRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RegResponse ответ на регистрацию пользователя
type RegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegResponse) Reset() {
	*x = RegResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegResponse) ProtoMessage() {}

func (x *RegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegResponse.ProtoReflect.Descriptor instead.
func (*RegResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *RegResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`       // логин для авторизации
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // пароль для авторизации
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCoupleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Couple *Couple `protobuf:"bytes,1,opt,name=couple,proto3" json:"couple,omitempty"`
}

func (x *CreateCoupleRequest) Reset() {
	*x = CreateCoupleRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCoupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCoupleRequest) ProtoMessage() {}

func (x *CreateCoupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCoupleRequest.ProtoReflect.Descriptor instead.
func (*CreateCoupleRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCoupleRequest) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

type CreateCoupleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCoupleResponse) Reset() {
	*x = CreateCoupleResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCoupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCoupleResponse) ProtoMessage() {}

func (x *CreateCoupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCoupleResponse.ProtoReflect.Descriptor instead.
func (*CreateCoupleResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{16}
}

type CreateCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type CreateCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{18}
}

type CreateBinaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binary *Binary `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *CreateBinaryRequest) Reset() {
	*x = CreateBinaryRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBinaryRequest) ProtoMessage() {}

func (x *CreateBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBinaryRequest.ProtoReflect.Descriptor instead.
func (*CreateBinaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{19}
}

func (x *CreateBinaryRequest) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

type CreateBinaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBinaryResponse) Reset() {
	*x = CreateBinaryResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBinaryResponse) ProtoMessage() {}

func (x *CreateBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBinaryResponse.ProtoReflect.Descriptor instead.
func (*CreateBinaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{20}
}

type CreateTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text *Text `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CreateTextRequest) Reset() {
	*x = CreateTextRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTextRequest) ProtoMessage() {}

func (x *CreateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTextRequest.ProtoReflect.Descriptor instead.
func (*CreateTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{21}
}

func (x *CreateTextRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type CreateTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTextResponse) Reset() {
	*x = CreateTextResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTextResponse) ProtoMessage() {}

func (x *CreateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTextResponse.ProtoReflect.Descriptor instead.
func (*CreateTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{22}
}

type ReadAllCouplesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadAllCouplesRequest) Reset() {
	*x = ReadAllCouplesRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCouplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCouplesRequest) ProtoMessage() {}

func (x *ReadAllCouplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCouplesRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCouplesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{23}
}

type ReadAllCouplesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Couples []*Couple `protobuf:"bytes,1,rep,name=couples,proto3" json:"couples,omitempty"`
}

func (x *ReadAllCouplesResponse) Reset() {
	*x = ReadAllCouplesResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCouplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCouplesResponse) ProtoMessage() {}

func (x *ReadAllCouplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCouplesResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCouplesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{24}
}

func (x *ReadAllCouplesResponse) GetCouples() []*Couple {
	if x != nil {
		return x.Couples
	}
	return nil
}

type ReadAllCardsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadAllCardsRequest) Reset() {
	*x = ReadAllCardsRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCardsRequest) ProtoMessage() {}

func (x *ReadAllCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCardsRequest.ProtoReflect.Descriptor instead.
func (*ReadAllCardsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{25}
}

type ReadAllCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *ReadAllCardsResponse) Reset() {
	*x = ReadAllCardsResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllCardsResponse) ProtoMessage() {}

func (x *ReadAllCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllCardsResponse.ProtoReflect.Descriptor instead.
func (*ReadAllCardsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{26}
}

func (x *ReadAllCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ReadAllBinariesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadAllBinariesRequest) Reset() {
	*x = ReadAllBinariesRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllBinariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllBinariesRequest) ProtoMessage() {}

func (x *ReadAllBinariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllBinariesRequest.ProtoReflect.Descriptor instead.
func (*ReadAllBinariesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{27}
}

type ReadAllBinariesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binaries []*Binary `protobuf:"bytes,1,rep,name=binaries,proto3" json:"binaries,omitempty"`
}

func (x *ReadAllBinariesResponse) Reset() {
	*x = ReadAllBinariesResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllBinariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllBinariesResponse) ProtoMessage() {}

func (x *ReadAllBinariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllBinariesResponse.ProtoReflect.Descriptor instead.
func (*ReadAllBinariesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{28}
}

func (x *ReadAllBinariesResponse) GetBinaries() []*Binary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

type ReadAllTextsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *ReadAllTextsRequest) Reset() {
	*x = ReadAllTextsRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTextsRequest) ProtoMessage() {}

func (x *ReadAllTextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTextsRequest.ProtoReflect.Descriptor instead.
func (*ReadAllTextsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{29}
}

func (x *ReadAllTextsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type ReadAllTextsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texts []*Text `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
}

func (x *ReadAllTextsResponse) Reset() {
	*x = ReadAllTextsResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllTextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllTextsResponse) ProtoMessage() {}

func (x *ReadAllTextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllTextsResponse.ProtoReflect.Descriptor instead.
func (*ReadAllTextsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{30}
}

func (x *ReadAllTextsResponse) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

type ReadCoupleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Couple *Couple `protobuf:"bytes,1,opt,name=couple,proto3" json:"couple,omitempty"`
}

func (x *ReadCoupleRequest) Reset() {
	*x = ReadCoupleRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCoupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoupleRequest) ProtoMessage() {}

func (x *ReadCoupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoupleRequest.ProtoReflect.Descriptor instead.
func (*ReadCoupleRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{31}
}

func (x *ReadCoupleRequest) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

type ReadCoupleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Couple *Couple `protobuf:"bytes,1,opt,name=couple,proto3" json:"couple,omitempty"`
}

func (x *ReadCoupleResponse) Reset() {
	*x = ReadCoupleResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCoupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoupleResponse) ProtoMessage() {}

func (x *ReadCoupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoupleResponse.ProtoReflect.Descriptor instead.
func (*ReadCoupleResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{32}
}

func (x *ReadCoupleResponse) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

type ReadCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *ReadCardRequest) Reset() {
	*x = ReadCardRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCardRequest) ProtoMessage() {}

func (x *ReadCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCardRequest.ProtoReflect.Descriptor instead.
func (*ReadCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{33}
}

func (x *ReadCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ReadCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *Card `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *ReadCardResponse) Reset() {
	*x = ReadCardResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCardResponse) ProtoMessage() {}

func (x *ReadCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCardResponse.ProtoReflect.Descriptor instead.
func (*ReadCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{34}
}

func (x *ReadCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ReadBinaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login  string  `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Binary *Binary `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *ReadBinaryRequest) Reset() {
	*x = ReadBinaryRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBinaryRequest) ProtoMessage() {}

func (x *ReadBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBinaryRequest.ProtoReflect.Descriptor instead.
func (*ReadBinaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{35}
}

func (x *ReadBinaryRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReadBinaryRequest) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

type ReadBinaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binary *Binary `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *ReadBinaryResponse) Reset() {
	*x = ReadBinaryResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBinaryResponse) ProtoMessage() {}

func (x *ReadBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBinaryResponse.ProtoReflect.Descriptor instead.
func (*ReadBinaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{36}
}

func (x *ReadBinaryResponse) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

type ReadTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Text  *Text  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ReadTextRequest) Reset() {
	*x = ReadTextRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTextRequest) ProtoMessage() {}

func (x *ReadTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTextRequest.ProtoReflect.Descriptor instead.
func (*ReadTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{37}
}

func (x *ReadTextRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ReadTextRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type ReadTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text *Text `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ReadTextResponse) Reset() {
	*x = ReadTextResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTextResponse) ProtoMessage() {}

func (x *ReadTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTextResponse.ProtoReflect.Descriptor instead.
func (*ReadTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{38}
}

func (x *ReadTextResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type DeleteCoupleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login  string  `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Couple *Couple `protobuf:"bytes,2,opt,name=couple,proto3" json:"couple,omitempty"`
}

func (x *DeleteCoupleRequest) Reset() {
	*x = DeleteCoupleRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCoupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCoupleRequest) ProtoMessage() {}

func (x *DeleteCoupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCoupleRequest.ProtoReflect.Descriptor instead.
func (*DeleteCoupleRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteCoupleRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteCoupleRequest) GetCouple() *Couple {
	if x != nil {
		return x.Couple
	}
	return nil
}

type DeleteCoupleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCoupleResponse) Reset() {
	*x = DeleteCoupleResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCoupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCoupleResponse) ProtoMessage() {}

func (x *DeleteCoupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCoupleResponse.ProtoReflect.Descriptor instead.
func (*DeleteCoupleResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{40}
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Card  *Card  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteCardRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{42}
}

type DeleteBinaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login  string  `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Binary *Binary `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *DeleteBinaryRequest) Reset() {
	*x = DeleteBinaryRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryRequest) ProtoMessage() {}

func (x *DeleteBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteBinaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{43}
}

func (x *DeleteBinaryRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteBinaryRequest) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

type DeleteBinaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBinaryResponse) Reset() {
	*x = DeleteBinaryResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryResponse) ProtoMessage() {}

func (x *DeleteBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryResponse.ProtoReflect.Descriptor instead.
func (*DeleteBinaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{44}
}

type DeleteTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Text  *Text  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DeleteTextRequest) Reset() {
	*x = DeleteTextRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextRequest) ProtoMessage() {}

func (x *DeleteTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextRequest.ProtoReflect.Descriptor instead.
func (*DeleteTextRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{45}
}

func (x *DeleteTextRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteTextRequest) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

type DeleteTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTextResponse) Reset() {
	*x = DeleteTextResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextResponse) ProtoMessage() {}

func (x *DeleteTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextResponse.ProtoReflect.Descriptor instead.
func (*DeleteTextResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{46}
}

type QuitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitRequest) Reset() {
	*x = QuitRequest{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRequest) ProtoMessage() {}

func (x *QuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRequest.ProtoReflect.Descriptor instead.
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{47}
}

type QuitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitResponse) Reset() {
	*x = QuitResponse{}
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitResponse) ProtoMessage() {}

func (x *QuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_keeper_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitResponse.ProtoReflect.Descriptor instead.
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_keeper_proto_rawDescGZIP(), []int{48}
}

var File_internal_grpc_proto_keeper_proto protoreflect.FileDescriptor

var file_internal_grpc_proto_keeper_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x4f, 0x54, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4f,
	0x54, 0x50, 0x22, 0x2c, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x22, 0x3e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x55, 0x50, 0x4c, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49,
	0x4e, 0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03,
	0x22, 0x1c, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84,
	0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbe, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x08,
	0x45, 0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x59,
	0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07, 0x45, 0x78, 0x70, 0x59, 0x65,
	0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x56, 0x43, 0x18, 0x05, 0x20, 0x01, 0x28, 0x11, 0x52,
	0x03, 0x43, 0x56, 0x43, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x54, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4f, 0x54, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22,
	0x2e, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x37, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f,
	0x75, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43,
	0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x3a, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x08, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x08, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x13,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x3a, 0x0a, 0x14, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x05,
	0x74, 0x65, 0x78, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f,
	0x75, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x22, 0x3c, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x22, 0x33, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x51, 0x0a, 0x11, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x3c,
	0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x49, 0x0a, 0x0f,
	0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x53, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f,
	0x75, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a,
	0x0b, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c,
	0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x94, 0x0b, 0x0a,
	0x0d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31,
	0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x03, 0x52, 0x65, 0x67, 0x12, 0x12, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x15, 0x2e, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x41, 0x75,
	0x74, 0x68, 0x12, 0x13, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x51, 0x75, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x51,
	0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65,
	0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4f, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x70, 0x6c,
	0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x1e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x78, 0x74, 0x73,
	0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c,
	0x6c, 0x54, 0x65, 0x78, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x54, 0x65,
	0x78, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x17, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x19, 0x2e,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x17, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65,
	0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x70, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x19, 0x2e, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_proto_keeper_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_keeper_proto_rawDescData = file_internal_grpc_proto_keeper_proto_rawDesc
)

func file_internal_grpc_proto_keeper_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_keeper_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_proto_keeper_proto_rawDescData)
	})
	return file_internal_grpc_proto_keeper_proto_rawDescData
}

var file_internal_grpc_proto_keeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_internal_grpc_proto_keeper_proto_goTypes = []any{
	(DataType_Type)(0),              // 0: keeper.DataType.Type
	(*PingRequest)(nil),             // 1: keeper.PingRequest
	(*PingResponse)(nil),            // 2: keeper.PingResponse
	(*VerifyRequest)(nil),           // 3: keeper.VerifyRequest
	(*VerifyResponse)(nil),          // 4: keeper.VerifyResponse
	(*DataType)(nil),                // 5: keeper.DataType
	(*Meta)(nil),                    // 6: keeper.Meta
	(*Couple)(nil),                  // 7: keeper.Couple
	(*Card)(nil),                    // 8: keeper.Card
	(*Binary)(nil),                  // 9: keeper.Binary
	(*Text)(nil),                    // 10: keeper.Text
	(*User)(nil),                    // 11: keeper.User
	(*RegRequest)(nil),              // 12: keeper.RegRequest
	(*RegResponse)(nil),             // 13: keeper.RegResponse
	(*AuthRequest)(nil),             // 14: keeper.AuthRequest
	(*AuthResponse)(nil),            // 15: keeper.AuthResponse
	(*CreateCoupleRequest)(nil),     // 16: keeper.CreateCoupleRequest
	(*CreateCoupleResponse)(nil),    // 17: keeper.CreateCoupleResponse
	(*CreateCardRequest)(nil),       // 18: keeper.CreateCardRequest
	(*CreateCardResponse)(nil),      // 19: keeper.CreateCardResponse
	(*CreateBinaryRequest)(nil),     // 20: keeper.CreateBinaryRequest
	(*CreateBinaryResponse)(nil),    // 21: keeper.CreateBinaryResponse
	(*CreateTextRequest)(nil),       // 22: keeper.CreateTextRequest
	(*CreateTextResponse)(nil),      // 23: keeper.CreateTextResponse
	(*ReadAllCouplesRequest)(nil),   // 24: keeper.ReadAllCouplesRequest
	(*ReadAllCouplesResponse)(nil),  // 25: keeper.ReadAllCouplesResponse
	(*ReadAllCardsRequest)(nil),     // 26: keeper.ReadAllCardsRequest
	(*ReadAllCardsResponse)(nil),    // 27: keeper.ReadAllCardsResponse
	(*ReadAllBinariesRequest)(nil),  // 28: keeper.ReadAllBinariesRequest
	(*ReadAllBinariesResponse)(nil), // 29: keeper.ReadAllBinariesResponse
	(*ReadAllTextsRequest)(nil),     // 30: keeper.ReadAllTextsRequest
	(*ReadAllTextsResponse)(nil),    // 31: keeper.ReadAllTextsResponse
	(*ReadCoupleRequest)(nil),       // 32: keeper.ReadCoupleRequest
	(*ReadCoupleResponse)(nil),      // 33: keeper.ReadCoupleResponse
	(*ReadCardRequest)(nil),         // 34: keeper.ReadCardRequest
	(*ReadCardResponse)(nil),        // 35: keeper.ReadCardResponse
	(*ReadBinaryRequest)(nil),       // 36: keeper.ReadBinaryRequest
	(*ReadBinaryResponse)(nil),      // 37: keeper.ReadBinaryResponse
	(*ReadTextRequest)(nil),         // 38: keeper.ReadTextRequest
	(*ReadTextResponse)(nil),        // 39: keeper.ReadTextResponse
	(*DeleteCoupleRequest)(nil),     // 40: keeper.DeleteCoupleRequest
	(*DeleteCoupleResponse)(nil),    // 41: keeper.DeleteCoupleResponse
	(*DeleteCardRequest)(nil),       // 42: keeper.DeleteCardRequest
	(*DeleteCardResponse)(nil),      // 43: keeper.DeleteCardResponse
	(*DeleteBinaryRequest)(nil),     // 44: keeper.DeleteBinaryRequest
	(*DeleteBinaryResponse)(nil),    // 45: keeper.DeleteBinaryResponse
	(*DeleteTextRequest)(nil),       // 46: keeper.DeleteTextRequest
	(*DeleteTextResponse)(nil),      // 47: keeper.DeleteTextResponse
	(*QuitRequest)(nil),             // 48: keeper.QuitRequest
	(*QuitResponse)(nil),            // 49: keeper.QuitResponse
}
var file_internal_grpc_proto_keeper_proto_depIdxs = []int32{
	6,  // 0: keeper.Couple.meta:type_name -> keeper.Meta
	6,  // 1: keeper.Card.meta:type_name -> keeper.Meta
	6,  // 2: keeper.Binary.meta:type_name -> keeper.Meta
	6,  // 3: keeper.Text.meta:type_name -> keeper.Meta
	11, // 4: keeper.RegRequest.user:type_name -> keeper.User
	7,  // 5: keeper.CreateCoupleRequest.couple:type_name -> keeper.Couple
	8,  // 6: keeper.CreateCardRequest.card:type_name -> keeper.Card
	9,  // 7: keeper.CreateBinaryRequest.binary:type_name -> keeper.Binary
	10, // 8: keeper.CreateTextRequest.text:type_name -> keeper.Text
	7,  // 9: keeper.ReadAllCouplesResponse.couples:type_name -> keeper.Couple
	8,  // 10: keeper.ReadAllCardsResponse.cards:type_name -> keeper.Card
	9,  // 11: keeper.ReadAllBinariesResponse.binaries:type_name -> keeper.Binary
	10, // 12: keeper.ReadAllTextsResponse.texts:type_name -> keeper.Text
	7,  // 13: keeper.ReadCoupleRequest.couple:type_name -> keeper.Couple
	7,  // 14: keeper.ReadCoupleResponse.couple:type_name -> keeper.Couple
	8,  // 15: keeper.ReadCardRequest.card:type_name -> keeper.Card
	8,  // 16: keeper.ReadCardResponse.card:type_name -> keeper.Card
	9,  // 17: keeper.ReadBinaryRequest.binary:type_name -> keeper.Binary
	9,  // 18: keeper.ReadBinaryResponse.binary:type_name -> keeper.Binary
	10, // 19: keeper.ReadTextRequest.text:type_name -> keeper.Text
	10, // 20: keeper.ReadTextResponse.text:type_name -> keeper.Text
	7,  // 21: keeper.DeleteCoupleRequest.couple:type_name -> keeper.Couple
	8,  // 22: keeper.DeleteCardRequest.card:type_name -> keeper.Card
	9,  // 23: keeper.DeleteBinaryRequest.binary:type_name -> keeper.Binary
	10, // 24: keeper.DeleteTextRequest.text:type_name -> keeper.Text
	1,  // 25: keeper.KeeperService.Ping:input_type -> keeper.PingRequest
	12, // 26: keeper.KeeperService.Reg:input_type -> keeper.RegRequest
	3,  // 27: keeper.KeeperService.Verify:input_type -> keeper.VerifyRequest
	14, // 28: keeper.KeeperService.Auth:input_type -> keeper.AuthRequest
	48, // 29: keeper.KeeperService.Quit:input_type -> keeper.QuitRequest
	16, // 30: keeper.KeeperService.CreateCouple:input_type -> keeper.CreateCoupleRequest
	18, // 31: keeper.KeeperService.CreateCard:input_type -> keeper.CreateCardRequest
	20, // 32: keeper.KeeperService.CreateBinary:input_type -> keeper.CreateBinaryRequest
	22, // 33: keeper.KeeperService.CreateText:input_type -> keeper.CreateTextRequest
	24, // 34: keeper.KeeperService.ReadAllCouples:input_type -> keeper.ReadAllCouplesRequest
	26, // 35: keeper.KeeperService.ReadAllCards:input_type -> keeper.ReadAllCardsRequest
	28, // 36: keeper.KeeperService.ReadAllBinaries:input_type -> keeper.ReadAllBinariesRequest
	30, // 37: keeper.KeeperService.ReadAllTexts:input_type -> keeper.ReadAllTextsRequest
	32, // 38: keeper.KeeperService.ReadCouple:input_type -> keeper.ReadCoupleRequest
	34, // 39: keeper.KeeperService.ReadCard:input_type -> keeper.ReadCardRequest
	36, // 40: keeper.KeeperService.ReadBinary:input_type -> keeper.ReadBinaryRequest
	38, // 41: keeper.KeeperService.ReadText:input_type -> keeper.ReadTextRequest
	40, // 42: keeper.KeeperService.DeleteCouple:input_type -> keeper.DeleteCoupleRequest
	42, // 43: keeper.KeeperService.DeleteCard:input_type -> keeper.DeleteCardRequest
	44, // 44: keeper.KeeperService.DeleteBinary:input_type -> keeper.DeleteBinaryRequest
	46, // 45: keeper.KeeperService.DeleteText:input_type -> keeper.DeleteTextRequest
	2,  // 46: keeper.KeeperService.Ping:output_type -> keeper.PingResponse
	13, // 47: keeper.KeeperService.Reg:output_type -> keeper.RegResponse
	4,  // 48: keeper.KeeperService.Verify:output_type -> keeper.VerifyResponse
	15, // 49: keeper.KeeperService.Auth:output_type -> keeper.AuthResponse
	49, // 50: keeper.KeeperService.Quit:output_type -> keeper.QuitResponse
	17, // 51: keeper.KeeperService.CreateCouple:output_type -> keeper.CreateCoupleResponse
	19, // 52: keeper.KeeperService.CreateCard:output_type -> keeper.CreateCardResponse
	21, // 53: keeper.KeeperService.CreateBinary:output_type -> keeper.CreateBinaryResponse
	23, // 54: keeper.KeeperService.CreateText:output_type -> keeper.CreateTextResponse
	25, // 55: keeper.KeeperService.ReadAllCouples:output_type -> keeper.ReadAllCouplesResponse
	27, // 56: keeper.KeeperService.ReadAllCards:output_type -> keeper.ReadAllCardsResponse
	29, // 57: keeper.KeeperService.ReadAllBinaries:output_type -> keeper.ReadAllBinariesResponse
	31, // 58: keeper.KeeperService.ReadAllTexts:output_type -> keeper.ReadAllTextsResponse
	33, // 59: keeper.KeeperService.ReadCouple:output_type -> keeper.ReadCoupleResponse
	35, // 60: keeper.KeeperService.ReadCard:output_type -> keeper.ReadCardResponse
	37, // 61: keeper.KeeperService.ReadBinary:output_type -> keeper.ReadBinaryResponse
	39, // 62: keeper.KeeperService.ReadText:output_type -> keeper.ReadTextResponse
	41, // 63: keeper.KeeperService.DeleteCouple:output_type -> keeper.DeleteCoupleResponse
	43, // 64: keeper.KeeperService.DeleteCard:output_type -> keeper.DeleteCardResponse
	45, // 65: keeper.KeeperService.DeleteBinary:output_type -> keeper.DeleteBinaryResponse
	47, // 66: keeper.KeeperService.DeleteText:output_type -> keeper.DeleteTextResponse
	46, // [46:67] is the sub-list for method output_type
	25, // [25:46] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_keeper_proto_init() }
func file_internal_grpc_proto_keeper_proto_init() {
	if File_internal_grpc_proto_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_proto_keeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_keeper_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_keeper_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_keeper_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_keeper_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_keeper_proto = out.File
	file_internal_grpc_proto_keeper_proto_rawDesc = nil
	file_internal_grpc_proto_keeper_proto_goTypes = nil
	file_internal_grpc_proto_keeper_proto_depIdxs = nil
}
