RUN_ADDRESS: localhost:8080
DB_PRODUCTIVE:  postgres://app:qqqQQQ123@localhost:5433/storage?sslmode=disable
SSL_SERTIFICATE_RELATIVE_PATH: certFile
SSL_SERTIFICATE_KEY_RELATIVE_PATH: certKey
DB_TEST:
SMTP_SERVER:
SMTP_LOGIN:
SMTP_PASSWORD:
MALE_TEMPLATE:
PASSWORD_KEY:
OTP_LIVE_TIME:
TOKEN_LIVE_TIME: